implemented task
ihorvasylenko23/spring_boot_project pull request #1
Opened 2023-09-01 18:32 UTC by ihorvasylenko23

2023-09-02 20:09 UTC, keda-vlad requested changes

2023-09-02 20:09 UTC, keda-vlad commented on src/main/java/mate/academy/repositiry/impl/BookRepositoryImpl.java
> +    }
U don't need @Autowired if u have only 1 constructor

2023-09-02 20:09 UTC, keda-vlad commented on src/main/java/mate/academy/SpringBootProjectApplication.java
> +    private BookService bookService;
Make injection here by constructor like in BookService

2023-09-02 20:09 UTC, keda-vlad commented on src/main/java/mate/academy/model/Book.java
> +    private String coverImage;
https://medium.com/@centizennationwide/mysql-naming-conventions-e3a6f6219efe
use  @Column(name = "cover_image")

2023-09-03 14:46 UTC, ohatsenko commented
I completely agree with Vlad

2023-09-04 12:41 UTC, ArtemReizer requested changes
GJ!) You can improve it

2023-09-04 12:41 UTC, ArtemReizer commented on src/main/java/mate/academy/repositiry/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Can`t insert book into DB: " + book);
if I'm not mistaken, throwing a simple RuntimeException is bad practice. You can throw HibernateException for example

2023-09-05 13:45 UTC, ohatsenko requested changes

2023-09-05 13:45 UTC, ohatsenko commented on src/main/java/mate/academy/model/Book.java
> +public class Book {
```suggestion
@Data
@Table(name = "books")
public class Book {

```

2023-09-05 13:45 UTC, ohatsenko commented on src/main/java/mate/academy/repositiry/impl/BookRepositoryImpl.java
> +    }
```suggestion
        }  catch (Exception e) {
            throw new EntityNotFoundException("Can`t get all books", e);
        }
    }

```

2023-09-05 13:55 UTC, ohatsenko approved these changes

2023-09-06 14:37 UTC, vovasalyha requested changes
GJ. Let's improve few things.

2023-09-06 14:37 UTC, vovasalyha commented on checkstyle.xml
> +</module>
Empty line

2023-09-06 14:37 UTC, vovasalyha commented on pom.xml
> +			<artifactId>spring-orm</artifactId>
All hibernate related dependencies are already bundled in `data-jpa` starter

2023-09-06 14:37 UTC, vovasalyha commented on pom.xml
> +			<artifactId>commons-dbcp2</artifactId>
Where are you using it?

2023-09-06 14:37 UTC, vovasalyha commented on pom.xml
> +				<version>3.1.1</version>
Use the latest version of plugin

2023-09-06 14:37 UTC, vovasalyha commented on src/main/java/mate/academy/SpringBootProjectApplication.java
> +        return new CommandLineRunner() {
Use lambda

2023-09-06 14:37 UTC, vovasalyha commented on src/main/java/mate/academy/SpringBootProjectApplication.java
> +    public SpringBootProjectApplication(BookService bookService) {
You can use lombok annotation to generate constructor.

2023-09-06 14:37 UTC, vovasalyha commented on src/main/java/mate/academy/model/Book.java
> +@Table(name = "books")
```suggestion
@Table(name = "book")
```

2023-09-06 14:37 UTC, vovasalyha commented on src/main/java/mate/academy/model/Book.java
> +    private String coverImage;
It's not necessary, hibernate default resolving strategy automatically parsing it to snake_case

2023-09-06 14:37 UTC, vovasalyha commented on src/main/java/mate/academy/repositiry/impl/BookRepositoryImpl.java
> +            session.save(book);
This method is deprecated in 6 version.

2023-09-06 14:37 UTC, vovasalyha commented on src/main/java/mate/academy/repositiry/impl/BookRepositoryImpl.java
> +            Query<Book> getAllBooksQuery = session.createQuery("from Book", Book.class);
```suggestion
            Query<Book> getAllBooksQuery = session.createQuery("FROM Book", Book.class);

```

2023-09-08 08:25 UTC, boroda4436 approved these changes
LGTM

2023-09-11 06:16 UTC, merged