Jv spring boot project hw 3
ihorvasylenko23/spring_boot_project pull request #3
Opened 2023-09-06 15:59 UTC by ihorvasylenko23

2023-09-06 18:47 UTC, SaiyaJ1N approved these changes
LGTM!!

2023-09-08 15:07 UTC, vovasalyha requested changes
GJ. Take a look on few suggestions. Also, you have here changes from all your PRs. Please check Bohdan's guide about several PRs at the time please.

2023-09-08 15:07 UTC, vovasalyha commented on src/main/java/mate/academy/repositiry/book/BookSpecificationBuilder.java
> +        if (searchParametrers.authors() != null && searchParametrers.authors().length > 0) {
you are duplicating the same code here many times. for me it's a good candidate for private method.

2023-09-08 15:07 UTC, vovasalyha commented on src/main/java/mate/academy/repositiry/book/BookSpecificationProviderManager.java
> +                .orElseThrow(() -> new RuntimeException("Can`t find correct "
better use `NoSuchElementException`

2023-09-08 15:07 UTC, vovasalyha commented on src/main/java/mate/academy/service/impl/BookServiceImpl.java
> +        Book updatedBook = bookMapper.toModel(requestDto);
if you are fetching existing book, just set new fields for that book entity which you fetched, you don't need to create new object.

2023-09-08 15:07 UTC, vovasalyha commented on src/main/java/mate/academy/service/impl/BookServiceImpl.java
> +        if (!bookRepository.existsById(id)) {
in most cases it's ok if entity is not found, just nothing will happen, but it's for you to decide.

2023-09-11 10:22 UTC, Vasul-Pankiv approved these changes

2023-09-11 10:22 UTC, Vasul-Pankiv commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/01-create-books-table.yaml
add empty line to the end of file

2023-09-11 10:59 UTC, merged