Jv spring boot project hw 4
ihorvasylenko23/spring_boot_project pull request #4
Opened 2023-09-08 05:20 UTC by ihorvasylenko23

2023-09-08 13:11 UTC, ohatsenko approved these changes

2023-09-08 16:01 UTC, vovasalyha requested changes
Please resolve your PRs so only changes related to the task are here. After that request review again

2023-09-18 15:19 UTC, vovasalyha requested changes
GJ. Let's improve it a bit

2023-09-18 15:19 UTC, vovasalyha commented on pom.xml
> +			<groupId>org.hibernate.validator</groupId>
It's better to prefer starters over concrete dependencies

2023-09-18 15:19 UTC, vovasalyha commented on src/main/java/mate/academy/dto/CreateBookRequestDto.java
>      private String isbn;
isbn has more validation rules

2023-09-18 15:19 UTC, vovasalyha commented on src/main/java/mate/academy/dto/CreateBookRequestDto.java
> +    @NotNull
if i'm not mistaken, by requirements, description and coverImage are nullable

2023-09-18 15:19 UTC, vovasalyha commented on src/main/java/mate/academy/repositiry/SpecificationProvider.java
> +    Specification<T> getSpecification(String [] params);
```suggestion
    Specification<T> getSpecification(String[] params);

```

2023-09-18 15:19 UTC, vovasalyha commented on src/main/java/mate/academy/repositiry/book/spec/PriceSpecificationProvider.java
> +                -> root.get("price").in(Arrays.stream(params).toArray());
I'm not sure if it's very useful to search something by list of prices (usually it's price ranges)

2023-09-18 15:19 UTC, vovasalyha commented on src/main/java/mate/academy/service/impl/BookServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2023-09-18 15:19 UTC, vovasalyha commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/01-create-books-table.yaml
empty line

2023-09-25 06:50 UTC, nacenik approved these changes
GJ, But fix some mistake after

2023-09-25 06:50 UTC, nacenik commented on src/main/java/mate/academy/service/impl/BookServiceImpl.java
> +    @Override
Not fixed

2023-09-25 06:50 UTC, nacenik commented on src/main/java/mate/academy/repositiry/book/spec/PriceSpecificationProvider.java
> +    public Specification<Book> getSpecification(Double minPrice, Double maxPrice) {
is this a good idea to use double when the price is BigDecimal?

2023-09-26 19:52 UTC, merged