Jv spring boot project hw 5
ihorvasylenko23/spring_boot_project pull request #5
Opened 2023-09-08 12:36 UTC by ihorvasylenko23

2023-09-08 14:52 UTC, AntonZhdanov approved these changes

2023-09-11 14:31 UTC, vovasalyha requested changes
GJ. Take a look on few comments. Also, before sending to review next time make sure you resolved issue with PRs, because I see here changes from other tasks.

2023-09-11 14:31 UTC, vovasalyha commented on src/main/java/mate/academy/repositiry/book/BookSpecificationBuilder.java
> +        if (searchParametrers.authors() != null && searchParametrers.authors().length > 0) {
You're duplicating a code many times here. For me it's a good candidate for private method

2023-09-11 14:31 UTC, vovasalyha commented on src/main/java/mate/academy/repositiry/book/BookSpecificationProviderManager.java
> +                .orElseThrow(() -> new RuntimeException("Can`t find correct "
better throw `NoSuchElementException` if required element in collection is not found

2023-09-11 14:31 UTC, vovasalyha commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/01-create-books-table.yaml
empty line

2023-09-27 14:35 UTC, vovasalyha approved these changes

2023-09-27 15:13 UTC, merged