Jv spring boot project hw 6
ihorvasylenko23/spring_boot_project pull request #6
Opened 2023-09-13 01:02 UTC by ihorvasylenko23

2023-09-13 15:45 UTC, ConfusedSatlan approved these changes

2023-09-18 12:53 UTC, andrii-hoienko requested changes
Nice, but some improvements required

2023-09-18 12:53 UTC, andrii-hoienko commented on pom.xml
> +			<version>2.2.0</version>
Please use property to specify version

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/controller/AuthController.java
> +  public UserLoginResponseDto login(@RequestBody UserLoginRequestDto requestDto) {
Please add Valid annotation to validate login request

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/controller/AuthController.java
> +    @PostMapping("/login")
```suggestion
  @PostMapping("/login")

```

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/controller/AuthController.java
> +  public UserLoginResponseDto login(@RequestBody UserLoginRequestDto requestDto) {
Please dont forget about allining

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/dto/CreateBookRequestDto.java
> +    @NotNull
It is possible to use notBlank annotation for such purposes https://www.baeldung.com/java-bean-validation-not-null-empty-blank

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/dto/user/UserLoginResponseDto.java
> +public class UserLoginResponseDto {
please use a lombok annotation to generate constructor

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/dto/user/UserRegistrationRequestDto.java
> +    private String firstName;
What if you deploy app for Japanese audience and there are a lot of people with 1 letter names and surnames like O for example?

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/exception/CustomGlobalExceptionHandler.java
> +        body.put("timestamp", LocalDateTime.now());
Please user some class instead of map to create error response

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
Do you really need GlobalExceptionHandler  and CustomGlobalExceptionHandler, is it possible to unite them?

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/model/User.java
> +    private Set<Role> roles = new HashSet<>();
Should this field be included in toString and EqualsHashCode?

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/security/CustomUserDetailsService.java
> +                .orElseThrow(() -> new RuntimeException("Can`t find user by email"));
By email or by username? Add details to message

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Please introduce some constants

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
magic number

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/security/JwtUtil.java
> +
```suggestion

```

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/service/impl/UserServiceImpl.java
> +            throw new RegistrationException("Unable to complete registration");
why unable? Add details to error message

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/service/impl/UserServiceImpl.java
> +        user.setPassword(passwordEncoder.encode(request.getPassword()));
it is possible to use mapper for mapping purposes?

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/validation/FieldMatch.java
> +    String message() default "Passwords do not match";
What if this annotation will be used not only for passwords?

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/validation/FieldMatchValidator.java
> +    private String firstFieldName;
bad names, field and fieldMatch significantly better

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/validation/FieldMatchValidator.java
> +    public boolean isValid(Object value, ConstraintValidatorContext context) {
It is possible to simplify if else statements in this method

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/java/mate/academy/validation/FieldValueUtil.java
> +        BeanWrapperImpl wrapper = new BeanWrapperImpl(object);
It is quite simple logic, not sure that it should be in separate class

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +      author: root
are you root? maybe even groot?

2023-09-18 12:53 UTC, andrii-hoienko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +  - include:
Please don`t forget about empty lines

2023-09-18 14:43 UTC, ihorvasylenko23 commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +      author: root
ahahahahah

2023-09-25 07:04 UTC, nacenik requested changes
Good, but fix your history for PR. Here are changes from previous PR related to pagination and swagger. They shouldn't be here.

2023-09-25 07:04 UTC, nacenik commented on src/main/java/mate/academy/model/Role.java
> +    @ManyToMany(mappedBy = "roles", fetch = FetchType.EAGER)
Is fetch type eager a good idea?

2023-09-27 07:08 UTC, nacenik approved these changes
LGTM! 👍

2023-09-27 07:08 UTC, nacenik commented on src/main/java/mate/academy/model/Role.java
> +    private Set<User> users;
How do you think do you need to have this field as a part of equals, hashcode and toString?

2023-09-27 08:02 UTC, ihorvasylenko23 commented on src/main/java/mate/academy/model/Role.java
> +    private Set<User> users;
thx))

2023-09-27 15:13 UTC, merged