Jv spring boot project hw 7
ihorvasylenko23/spring_boot_project pull request #7
Opened 2023-09-18 02:11 UTC by ihorvasylenko23

2023-09-18 10:01 UTC, IvanFadieiev requested changes
Good solution! Some things might be improved :)

2023-09-18 10:01 UTC, IvanFadieiev commented on src/main/java/mate/academy/controller/BookController.java
>      }
It's possible to add @RequiredArgsConstructor and remove this constructor

2023-09-18 10:01 UTC, IvanFadieiev commented on src/main/java/mate/academy/controller/CategoryController.java
> +    }
It should be specific role for this controller

2023-09-18 10:01 UTC, IvanFadieiev commented on src/main/java/mate/academy/controller/CategoryController.java
> +    }
Also here, add roles, please :)

2023-09-18 10:01 UTC, IvanFadieiev commented on src/main/java/mate/academy/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
As far as I remember using FetchType EAGER is considered a bad practice. Is it possible to leave default fetch type LAZY?

2023-09-27 00:33 UTC, ihorvasylenko23 commented on src/main/java/mate/academy/controller/CategoryController.java
> +    }
but this controller is for the “User” role, and this role is the default in my project and I don’t have to specify it, if I’m not mistaken. Not sure, let it stay like this until the mentors check

2023-09-27 00:34 UTC, ihorvasylenko23 commented on src/main/java/mate/academy/controller/CategoryController.java
> +    }
same

2023-09-27 00:37 UTC, ihorvasylenko23 commented on src/main/java/mate/academy/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
I think that in this case it would be possible to leave Eager, but I agree that it would be good practice to avoid this. That's why I'll do it))

2023-09-27 14:51 UTC, vovasalyha approved these changes
Approving, but please take a look at the comments

2023-09-27 14:51 UTC, vovasalyha commented on src/main/java/mate/academy/service/impl/CategoryServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2023-09-27 14:51 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/06-create-categories-table.yaml
> +                    nullable: false
empty line

2023-09-27 14:51 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/07-create-book-categories-table.yaml
> +                    primaryKey: true
empty line

2023-09-27 14:51 UTC, vovasalyha commented on src/main/java/mate/academy/service/impl/CategoryServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2023-09-27 15:14 UTC, merged