Jv spring boot project hw 8
ihorvasylenko23/spring_boot_project pull request #8
Opened 2023-09-21 06:21 UTC by ihorvasylenko23

2023-09-21 12:05 UTC, ArtemReizer requested changes
GJ) Some minor changes request, but good in general

2023-09-21 12:05 UTC, ArtemReizer commented on src/main/java/mate/academy/controller/ShoppingCartController.java
> +    @GetMapping
methods of the ShoppingCartController should be available only for users with role USER

2023-09-21 12:05 UTC, ArtemReizer commented on src/main/java/mate/academy/service/impl/CartItemServiceImpl.java
> +        return optionalCartItem.map(cartItemMapper::toDto).orElse(null);
I guess it is better to use .orElseThrow() and throw exception

2023-09-21 12:05 UTC, ArtemReizer commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +    public ShoppingCartDto addToCart(AddToCartRequestDto requestDto, Long userId) {
as for me this method isn't readable enough. Try to split this method into different methods

2023-09-21 12:05 UTC, ArtemReizer commented on src/main/resources/liquibase.properties
> +password=Vika07012000
nice password)))))

2023-09-21 12:05 UTC, ArtemReizer commented on src/test/resources/application.properties
> +jwt.secret=esliyan0shukand1bobernagoloveetoneznachitchtojazhenschinailibalerina
)))))

2023-09-27 15:38 UTC, vovasalyha requested changes
GJ. Let's improve it

2023-09-27 15:38 UTC, vovasalyha commented on src/main/java/mate/academy/controller/ShoppingCartController.java
> +    @GetMapping
Agree, I doubt that admins should have shopping cart, which means for admins this endpoint can be irrelevant

2023-09-27 15:38 UTC, vovasalyha commented on src/main/java/mate/academy/controller/ShoppingCartController.java
> +        Long userId = user.getId();
I think this line can be inlined with the next one

2023-09-27 15:38 UTC, vovasalyha commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +    @Transactional
```suggestion
    @Override
    @Transactional
```

2023-09-27 15:38 UTC, vovasalyha commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +    private User getUserById(Long userId) {
this method should not be here, it should be in user service

2023-09-27 15:38 UTC, vovasalyha commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +    private Book getBookById(Long bookId) {
this method should not be here, it should be in book service

2023-09-27 15:38 UTC, vovasalyha commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +        if (optionalCartItem.isEmpty()) {
`orElseThrow`

2023-09-27 15:38 UTC, vovasalyha commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```
Please don't forget about this annotation in all methods that modify something in Database and consist of more than 1 step

2023-09-27 15:38 UTC, vovasalyha commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +    public ShoppingCartDto updateCartItem(Long cartItemId, int quantity) {
add validation that item belongs to the user, because for now any user can modify any other users items

2023-09-27 15:38 UTC, vovasalyha commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +        cartItemRepository.deleteById(cartItemId);
the same with delete. any user can delete any item now

2023-09-28 07:10 UTC, nacenik approved these changes
LGTM! 👍

2023-09-28 07:10 UTC, nacenik commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +    public void deleteCartItem(Long userId, Long cartItemId) {
Add transactional too

2023-10-23 22:49 UTC, merged