Jv spring boot project hw 9
ihorvasylenko23/spring_boot_project pull request #9
Opened 2023-09-24 23:11 UTC by ihorvasylenko23

2023-09-25 13:27 UTC, ArtemReizer approved these changes
LGTM!)

2023-09-27 16:05 UTC, vovasalyha requested changes
GJ. Let's improve it a bit

2023-09-27 16:05 UTC, vovasalyha commented on src/main/java/mate/academy/model/OrderItem.java
> +    private Order order;
exclude all relations from equals, hashcode and toString

2023-09-27 16:05 UTC, vovasalyha commented on src/main/java/mate/academy/service/impl/BookServiceImpl.java
>      @Override
```suggestion
    @Override
    @Transactional
```

2023-09-27 16:05 UTC, vovasalyha commented on src/main/java/mate/academy/service/impl/OrderItemServiceImpl.java
> +        Order order = orderRepository.findById(orderId)
better move it to the order service

2023-09-27 16:05 UTC, vovasalyha commented on src/main/java/mate/academy/service/impl/OrderServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(user.getId())
move this to shopping cart service

2023-09-27 16:05 UTC, vovasalyha commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +        Optional<CartItem> optionalCartItem = cartItemRepository.findById(cartItemId);
simply use `deleteById` method, it would also change `deleted` value to true, because you set it in the entity(if you didn't then please set it). Also make sure that item belongs to the user

2023-09-28 07:17 UTC, nacenik approved these changes
LGTM! 👍

2023-09-28 07:17 UTC, nacenik commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +    public void deleteCartItem(Long userId, Long cartItemId) {
what do you think should this method be transactional?

2023-10-23 22:49 UTC, merged